const LOCATION_NAMES: Record<string, string> = {
  istanbul: "İstanbul",
  gaziosmanpasa: "Gaziosmanpaşa",
  sultangazi: "Sultangazi",
  eyup: "Eyüpsultan",
  basaksehir: "Başakşehir",
  bagcilar: "Bağcılar",
  bayrampasa: "Bayrampaşa",
  esenler: "Esenler",
  gungoren: "Güngören",
  barbaros: "Barbaros",
  baglarbasi: "Bağlarbaşı",
  karadeniz: "Karadeniz",
  karayollari: "Karayolları",
  merkez: "Merkez",
  mevlana: "Mevlana",
  sarigol: "Sarıgöl",
  seyrantepe: "Seyrantepe",
  sultanciftligi: "Sultançiftliği",
  topcular: "Topçular",
  turkoba: "Türkoba",
  yesilpinar: "Yeşilpınar",
  karlitepe: "Karlıtepe",
  kucukkoy: "Küçükköy",
  fevzicakmak: "Fevziçakmak",
  ufuk: "Ufuk",
  yenidogan: "Yenidoğan",
  pazarici: "Pazariçi",
  atisalani: "Atışalanı",
  karaagac: "Karaağaç",
  cebeci: "Cebeci",
  ugurmumcu: "Uğur Mumcu",
  habibler: "Habibler",
  ikitelli: "İkitelli",
  "50-yil": "50. Yıl",
  "75-yil": "75. Yıl",
  cumhuriyet: "Cumhuriyet",
  esentepe: "Esentepe",
  "eski-habipler": "Eski Habipler",
  ismetpasa: "İsmetpaşa",
  malkocoglu: "Malkoçoğlu",
  yayla: "Yayla",
  "yunus-emre": "Yunus Emre",
  "zubeyde-hanim": "Zübeyde Hanım",
  gazi: "Gazi",
  alibeykoy: "Alibeyköy",
  agacli: "Ağaçlı",
  akpinar: "Akpınar",
  aksemsettin: "Akşemsettin",
  circir: "Çırçır",
  ciftalan: "Çiftalan",
  defterdar: "Defterdar",
  dugmeciler: "Düğmeciler",
  emniyettepe: "Emniyettepe",
  "eyupsultan-merkez": "Eyüpsultan Merkez",
  gokturk: "Göktürk",
  guzeltepe: "Güzeltepe",
  isiklar: "Işıklar",
  ihsaniye: "İhsaniye",
  islambey: "İslambey",
  karadolap: "Karadolap",
  kemerburgaz: "Kemerburgaz",
  mimarsinan: "Mimarsinan",
  mithatpasa: "Mithatpaşa",
  nisanca: "Nişanca",
  odayeri: "Odayeri",
  pirincci: "Pirinççi",
  "rami-cuma": "Rami Cuma",
  "rami-yeni": "Rami Yeni",
  sakarya: "Sakarya",
  silahtaraga: "Silahtarağa",
  "5-levent": "5. Levent",
  rami: "Rami",
  gungorensanayi: "Güngören Sanayi",
  baris: "Barış",
  yenimahalle: "Yenimahalle",
  baglar: "Bağlar",
  goztepe: "Göztepe",
  "barbaros-hayrettinpasa": "Barbaros Hayrettinpaşa",
  hurriyet: "Hürriyet",
  "kazim-karabekir": "Kazım Karabekir",
  semsipasa: "Şemsipaşa",
  "yeni-mahalle": "Yeni Mahalle",
  yildiztabya: "Yıldıztabya",
  yildirim: "Yıldırım",
  kartaltepe: "Kartaltepe",
  muratpasa: "Muratpaşa",
  altintepsi: "Altıntepsi",
  cevatpasa: "Cevatpaşa",
  kocatepe: "Kocatepe",
  orta: "Orta",
  terazidere: "Terazidere",
  vatan: "Vatan",
  zafer: "Zafer",
  ataturk: "Atatürk",
  "15-temmuz": "15 Temmuz",
  birlik: "Birlik",
  "cifte-havuzlar": "Çifte Havuzlar",
  davutpasa: "Davutpaşa",
  fatih: "Fatih",
  kemer: "Kemer",
  menderes: "Menderes",
  "mimar-sinan": "Mimar Sinan",
  "namik-kemal": "Namık Kemal",
  "nine-hatun": "Nine Hatun",
  orucreis: "Oruçreis",
  tuna: "Tuna",
  "turgut-reis": "Turgut Reis",
  "yavuz-selim": "Yavuz Selim",
  sehitler: "Şehitler",
  "yesil-vadi": "Yeşil Vadi",
};

export function formatLocationName(slugPart: string) {
  if (!slugPart) return "";

  return LOCATION_NAMES[slugPart.toLowerCase()] ||
    slugPart.charAt(0).toUpperCase() + slugPart.slice(1);
}
